### ISSUE TITLE
CLI should resolve env vars

### ISSUE THREAD

**Issue by niktekusho** [niktekusho/mas-piano-validator-cli#9]
This might be a Windows-only problem, but passing in a path contained in an env var is not currently working. It seems Powershell does not like variable expansion.

**Command example**:

```sh
maspv "$env:MAS\game\mod_assets\piano\songs"
```

**Error**:

```
Error: ENOENT: no such file or directory, stat '\game\mod_assets\piano\songs'
    at Object.statSync (fs.js:872:3)
    at main (C:\Users\blablabla\AppData\Roaming\npm\node_modules\mas-piano-validator-cli\index.js:57:19)
    at Object.<anonymous> (C:\Users\blablabla\AppData\Roaming\npm\node_modules\mas-piano-validator-cli\cli.js:19:1)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:499:15)
```

**Comment by niktekusho** [comment]
I tested on a Docker container, and I haven't been able to reproduce...

## Steps
**Command**:
```sh
docker run -it --rm mhart/alpine-node:10 sh
```

Once inside the container...

```sh
$ npm i -g mas-piano-validator-cli
$ printenv # Just to see the environment vars available
$ maspv "$HOME" # This works (surprising quick I'd say)
⚠  warning   All files are NOT valid Monika After Story piano songs.
...
```

**Comment by niktekusho** [comment]
Ok... after a few attempts I managed to make it work: the syntax in Powershell requires *scope* around the environment variable when you use it to compose a path.

**Examples**:

```sh
$ maspv "$env:MAS"
# Will print validation results for each file in the Monika After Story
# installation directory (MAS is a custom environment variable)
```

```sh
$ maspv "${env:MAS}\piano_songs"
# Will print validation results for each file in the 'piano_songs' sub-directory
# in Monika After Story installation directory (MAS is a custom environment variable)
```
